### ISSUE TITLE
No virtual method circleCrop()

### ISSUE THREAD

**Issue by ananthuma** [bxute/StoryView#11]
During runtime i'm getting this error. This is the stack
    java.lang.NoSuchMethodError: No virtual method circleCrop()Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.d33pzz.tato-y5sWp5EtIndwGu2QG3etxA==/base.apk)
        at xute.storyview.StoryView.loadFirstImageBitamp(StoryView.java:160)
        at xute.storyview.StoryView.setImageUris(StoryView.java:111)
        at com.d33pzz.tato.StatusScreenActivity$5.onDataChange(StatusScreenActivity.java:146)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@19.3.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@19.3.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.3.0:55)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
I/Process: Sending signal. PID: 8266 SIG: 9

**Comment by MamboBryan** [comment]
Got same issue when using latest glide version

**Comment by pratistha-05** [comment]
Got the same issue ..is there any solution?
